// Pre-render routes for SEO - Static Site Generation
// These routes will be pre-rendered at build time for better SEO

export const PRERENDER_ROUTES = [
  // Homepage
  '/',
  
  // Main Service Hubs
  '/general-notary',
  '/loan-signings',
  '/estate-plans',
  '/real-estate',
  '/apostille',
  '/business-services',
  '/college-18-plus',
  '/personal-family',
  '/healthcare-notary',
  '/real-estate-notary',
  '/business-banking',
  '/legal-court',
  '/international-apostille',
  '/vehicles-dmv',
  '/insurance-retirement',
  '/wills-trusts-estates',
  '/other-notary',
  
  // Static Pages
  '/faq',
  '/about',
  '/contact',
  '/pricing',
  '/documents',
  '/service-areas',
  '/book-now',
  '/privacy-policy',
  '/terms-of-service',
  
  // Seasonal Landing Pages
  '/tax-season-notary',
  '/back-to-school-documents',
  '/home-buying-season-notary',
  '/year-end-planning-notary',
  
  // Blog Home & Categories
  '/blog',
  '/blog/general-notary-guides',
  '/blog/loan-signing-guides',
  '/blog/real-estate-guides',
  '/blog/estate-planning-guides',
  '/blog/apostille-guides',
  '/blog/business-guides',
  '/blog/healthcare-guides',
  '/blog/immigration-guides',
  '/blog/military-guides',
  '/blog/education-guides',
  
  // Individual Blog Posts
  '/blog/general-notary-what-to-bring',
  '/blog/mobile-vs-shipping-store',
  '/blog/hcpoa-living-will-guide',
  '/blog/hospital-notary-what-to-expect',
  '/blog/wills-trusts-poa-checklist',
  '/blog/what-happens-loan-signing',
  '/blog/how-apostille-works',
  '/blog/remote-hire-i9-steps',
  '/blog/college-18-plus-starter-pack',
  '/blog/title-transfer-checklist',
  '/blog/affidavit-jurat-acknowledgment',
  '/blog/beneficiary-change-forms',
  '/blog/investor-notarizations',
  '/blog/seller-signing-day',
  '/blog/scanback-timing-explained',
  '/blog/apostille-processing-times',
  '/blog/notary-vs-ron-rin',
  '/blog/business-contract-notarization',
  '/blog/international-travel-consent',
  '/blog/small-estate-affidavit-executor-tips',
  '/blog/jail-notarization-process',
  '/blog/after-hours-emergency-notary',
  '/blog/witness-requirements',
  '/blog/expired-id-options',
  '/blog/name-mismatch-aka-affidavit',
  '/blog/deeds-explained',
  '/blog/poa-pitfalls-and-readiness',
  '/blog/apostille-school-docs',
  '/blog/translator-affidavit-notary',
  '/blog/trust-certification-for-banks',
  '/blog/notary-fees-and-mobile-travel',
  '/blog/what-notaries-cannot-do',
  '/blog/estate-planning-guides',
  '/blog/ohio-buyer-seller-loan-signing-checklist',
  '/blog/refi-heloc-notary-errors-to-avoid-ohio',
  '/blog/scanbacks-printing-mobile-loan-closings-ohio',
  '/blog/hospital-rehab-loan-signings-ohio',
  '/blog/ohio-wills-poa-what-notaries-can-and-cant-do',
  '/blog/healthcare-directives-notary-ohio-bedside',
  '/blog/certification-of-trust-notary-ohio',
  '/blog/witnesses-for-wills-poa-ohio-local-norms',
  '/blog/vendor-packets-affidavits-notary-ohio',
  '/blog/contracts-title-authority-notary-ohio',
  '/blog/permits-licensing-notary-same-day-ohio',
  '/blog/hr-i9-vs-notary-ohio',
  '/blog/hospital-notary-checklist-ohio',
  '/blog/senior-communities-notary-poa-healthcare-ohio',
  '/blog/urgent-notary-same-day-ohio-hospitals',
  '/blog/hospital-notary-id-problems-ohio',
  '/blog/immigration-documents-notary-guide',
  '/blog/military-veterans-notary-guide',
  '/blog/healthcare-documents-notary-guide',
  '/blog/ohio-car-title-transfer-requirements',
  
  // Resources Hub
  '/resources',
  
  // County Hub Pages (consolidated from ~230 thin location blog pages)
  '/blog/notary-guide-hamilton-county-ohio',
  '/blog/notary-guide-warren-county-ohio',
  '/blog/notary-guide-montgomery-county-ohio',
  '/blog/notary-guide-butler-county-ohio',
  '/blog/notary-guide-greene-county-ohio',
  '/blog/notary-guide-clinton-county-ohio',

  // Kept-live city pages (have indexing traction)
  '/blog/loan-signing-guides-mason-ohio',
  '/blog/healthcare-guides-cincinnati-ohio',

  // Miami County Cities
  '/service/miami-county/troy-45373',
  '/service/miami-county/piqua-45356',
  '/service/miami-county/tipp-city-45371',
  '/service/miami-county/covington-45318',
  '/service/miami-county/west-milton-45383',
];

export default PRERENDER_ROUTES;
