// Pre-render routes for SEO - Static Site Generation
// These routes will be pre-rendered at build time for better SEO

export const PRERENDER_ROUTES = [
  // Homepage
  '/',
  
  // Main Service Hubs
  '/general-notary',
  '/loan-signings',
  '/estate-plans',
  '/real-estate',
  '/apostille',
  '/business-services',
  '/college-18-plus',
  '/personal-family',
  '/healthcare-notary',
  '/real-estate-notary',
  '/business-banking',
  '/legal-court',
  '/international-apostille',
  '/vehicles-dmv',
  '/insurance-retirement',
  '/wills-trusts-estates',
  '/other-notary',
  
  // Static Pages
  '/faq',
  '/about',
  '/contact',
  '/pricing',
  '/service-areas',
  '/book-now',
  '/privacy-policy',
  '/terms-of-service',
  
  // Blog Home & Categories
  '/blog',
  '/blog/loan-signing',
  '/blog/estate-planning',
  '/blog/real-estate',
  '/blog/apostille',
  '/blog/business',
  '/blog/general-notary',
  '/blog/healthcare',
  
  // Individual Blog Posts
  '/blog/general-notary-what-to-bring',
  '/blog/mobile-vs-shipping-store',
  '/blog/hcpoa-living-will-guide',
  '/blog/hospital-notary-what-to-expect',
  '/blog/wills-trusts-poa-checklist',
  '/blog/what-happens-loan-signing',
  '/blog/how-apostille-works',
  '/blog/remote-hire-i9-steps',
  '/blog/college-18-plus-starter-pack',
  '/blog/title-transfer-checklist',
  '/blog/affidavit-jurat-acknowledgment',
  '/blog/beneficiary-change-forms',
  '/blog/investor-notarizations',
  '/blog/seller-signing-day',
  '/blog/scanback-timing-explained',
  '/blog/apostille-processing-times',
  '/blog/notary-vs-ron-rin',
  '/blog/business-contract-notarization',
  '/blog/international-travel-consent',
  '/blog/small-estate-affidavit-executor-tips',
  '/blog/jail-notarization-process',
  '/blog/after-hours-emergency-notary',
  '/blog/witness-requirements',
  '/blog/expired-id-options',
  '/blog/name-mismatch-aka-affidavit',
  '/blog/deeds-explained',
  '/blog/poa-pitfalls-and-readiness',
  '/blog/apostille-school-docs',
  '/blog/translator-affidavit-notary',
  '/blog/trust-certification-for-banks',
  '/blog/notary-fees-and-mobile-travel',
  '/blog/what-notaries-cannot-do',
  '/blog/estate-planning-guides',
  '/blog/ohio-buyer-seller-loan-signing-checklist',
  '/blog/refi-heloc-notary-errors-to-avoid-ohio',
  '/blog/scanbacks-printing-mobile-loan-closings-ohio',
  '/blog/hospital-rehab-loan-signings-ohio',
  '/blog/ohio-wills-poa-what-notaries-can-and-cant-do',
  '/blog/healthcare-directives-notary-ohio-bedside',
  '/blog/certification-of-trust-notary-ohio',
  '/blog/witnesses-for-wills-poa-ohio-local-norms',
  '/blog/vendor-packets-affidavits-notary-ohio',
  '/blog/contracts-title-authority-notary-ohio',
  '/blog/permits-licensing-notary-same-day-ohio',
  '/blog/hr-i9-vs-notary-ohio',
  '/blog/hospital-notary-checklist-ohio',
  '/blog/senior-communities-notary-poa-healthcare-ohio',
  '/blog/urgent-notary-same-day-ohio-hospitals',
  '/blog/hospital-notary-id-problems-ohio',
  
  // Location Pages
  '/notary-cincinnati-45202',
  '/notary-mason-45040',
  '/notary-dayton-45402',
  '/notary-west-chester-45069',
  '/notary-springdale-45246',
  '/notary-kettering-45429',
  '/notary-lebanon-45036',
  '/general-notary/hamilton/blue-ash',
  '/power-of-attorney-warren-county-lebanon',
  '/loan-signing-dayton-montgomery-county',
  '/general-notary-hamilton-county-cincinnati',
  '/wills-estates-warren-county-mason',
];

export default PRERENDER_ROUTES;
