
INSERT INTO testimonials (reviewer_name, rating, review_text, review_date, service_type, location, source, verified) VALUES
('Success Properties', 5, 'Came all the way to West Chester to do a closing, notarized all the papers and gave me advice on lending. Awesome guy to work with.', '2025-01-10', 'loan-signing', 'West Chester', 'google', true),
('Rohit Chauhan', 5, 'Professional and punctual. Explained the signing documents for mortgage in detail!!', '2025-01-08', 'mortgage', 'South Lebanon', 'google', true),
('Debra Gilliam', 5, 'He did a great job. Very thorough with details.', '2025-01-05', 'general', NULL, 'google', true),
('Esther Webb', 5, 'Terri came to our house and did a real estate closing. He did a wonderful job and was very professional. Highly recommend him.', '2025-01-03', 'real-estate', NULL, 'google', true),
('Casey Sellers', 5, 'On time, very knowledgeable and professional. I would use Terry again and recommend him to others.', '2024-12-28', 'mobile-notary', NULL, 'google', true),
('Ryan Bissman', 5, 'Terry was approachable and kind. Appointment went very quickly and easy process. Got my new home with my new job, so grateful!', '2024-12-20', 'loan-signing', 'Lebanon', 'google', true),
('Deneen Wells', 5, 'Terry May was fantastic helping us with our refinancing!', '2024-12-15', 'refinance', NULL, 'google', true),
('Brenda Thomas', 5, 'Excellent service for estate document notarization.', '2024-12-10', 'estate', NULL, 'google', true),
('Marnie Smith', 5, 'Terry did great service to me in helping with estate matters. Helped me sell my grandparents'' home in Mason.', '2024-12-05', 'estate', 'Mason', 'google', true),
('B Cloonan', 5, 'Terry was absolutely great. I had a very small window of time to complete my documents for a real estate transaction. He was flexible, responsive, and most importantly, experienced. As a real estate professional I see what can go wrong! This went extremely smoothly with Terry!', '2024-11-28', 'real-estate', NULL, 'google', true),
('David Bias', 5, 'I recently met with Terry to have a document notarized. Terry was very accommodating and responsive! I would absolutely trust Terry with any future notary needs.', '2024-11-20', 'general', NULL, 'google', true),
('Amber', 5, 'I recently had a document notarized by Terry and was impressed by his professionalism and efficiency. The process was quick and straightforward. Terry took the time to explain each step clearly, making the experience easy. I appreciate how friendly and patient he was throughout.', '2024-11-15', 'general', NULL, 'google', true),
('Paige Santini', 5, 'Terry did a wonderful job. Very pleasant and friendly. Very knowledgeable.', '2024-11-10', 'general', 'Xenia', 'google', true),
('Tony Santini', 5, 'Very professional and easy to deal with. Travelled to Xenia for my notarization.', '2024-11-08', 'general', 'Xenia', 'google', true),
('Durgha Rajamanickam', 5, 'Terry was very helpful and flexible with us during closing. He was very patient and gave great explanation on the closing documents. We had a wonderful experience.', '2024-11-01', 'loan-signing', NULL, 'google', true),
('Timothy McDaniel', 5, 'Came to Springboro late night very friendly punctual and did a great job!!! Got me my truck!', '2024-10-25', 'title-transfer', 'Springboro', 'google', true),
('Eli S', 5, 'Late night, last minute arrival. Friendly, came to springboro very quickly!', '2024-10-20', 'title-transfer', 'Springboro', 'google', true),
('Michael Casciato', 5, 'Terry was well prepared, efficient, and very friendly. He came to our house at our convenience and was really easy to work with.', '2024-10-15', 'general', 'Maineville', 'google', true),
('Heather Schmit', 5, 'Terry May is phenomenal! Great service and flexible to meet clients at their residence to accomplish timely notary services. As a military family, his flexibility was invaluable.', '2024-10-10', 'mobile-notary', 'Beavercreek', 'google', true),
('Jun Les', 5, 'I recently worked with Terry May for notary services in Montgomery County Ohio, and was extremely pleased with his professionalism and efficiency. He handled the apostille process for an international document flawlessly.', '2024-10-05', 'apostille', 'Montgomery County', 'google', true),
('David Keith', 5, 'Awesome service! Terry met us at our home after hours on a Friday night. Super friendly and efficient!', '2024-09-28', 'mobile-notary', NULL, 'google', true),
('Jill Van Auken', 5, 'Terry was quick to respond and answered all my questions. He was flexible to meet at my convenience and was very professional. Highly recommend!', '2024-09-20', 'mobile-notary', NULL, 'google', true),
('Tina Allen', 5, 'Terry came out to Clinton county for a closing. Great service all around!', '2024-09-15', 'loan-signing', 'Wilmington', 'google', true),
('James Lakin', 5, 'Did great service in Wilmington Ohio! Notarized camper title transfer documents quickly and professionally.', '2024-09-10', 'title-transfer', 'Wilmington', 'google', true),
('Jeffery Lay', 5, 'Terry is a terrific human being and total professional. He is always available and willing to travel to your location.', '2024-09-05', 'general', 'Lebanon', 'google', true),
('Bob Hull', 5, 'Loan closing at my home in Lebanon, OH, Warren County, was a pleasure working with Terry May. Prompt, friendly, and well organized.', '2024-08-28', 'loan-signing', 'Lebanon', 'google', true),
('Ollie Lawson', 5, 'Terry was very informative and explained everything in detail about my documents, helping me buy my first house. He drove 30+ mins to Germantown for us!', '2024-08-20', 'first-home', 'Germantown', 'google', true),
('Walter Janz', 5, 'Terry did a great job covering a last minute closing for us in Cincinnati. Professional and thorough!', '2024-08-15', 'loan-signing', 'Cincinnati', 'google', true),
('Nathaniel Steinhoff', 5, 'I can''t recommend Terry highly enough. I''m a real estate professional who''s been in the business for more than a decade and Terry is one of the best notaries I''ve worked with.', '2024-08-10', 'real-estate', NULL, 'google', true),
('Andy Culberson', 5, 'Terry May did a great job and was very informative during my closing. Would definitely use again!', '2024-08-05', 'loan-signing', NULL, 'google', true),
('Bret Biggs', 5, 'Terry was punctual, professional, and easy to work with. Made the whole notarization process smooth and stress-free.', '2024-07-28', 'general', NULL, 'google', true),
('Stephen Faris', 5, 'He came on Sunday at his personal expense to help us with urgent documents. Above and beyond service!', '2024-07-20', 'urgent', NULL, 'google', true),
('Michele Weintraub', 5, 'Running a successful signing agency for the last 16 years. Terry is an excellent notary signing agent. Professional, reliable, and thorough with every signing.', '2024-07-15', 'loan-signing', NULL, 'google', true),
('Joanna Sosiewicz', 5, 'Terry was of great assistance when he went to our client''s house to complete an urgent signing. Very professional and accommodating!', '2024-07-10', 'mobile-notary', NULL, 'google', true),
('Karolina Sites Smart', 5, 'Excellent notary service. Professional and efficient!', '2024-07-05', 'general', NULL, 'google', true);
