// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfbmbbslubgrwsguxcqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmYm1iYnNsdWJncndzZ3V4Y3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjAzOTMsImV4cCI6MjA3NDIzNjM5M30.cDJW7sgKYSrWhX9D7ACIUKbPQE3kfXu-t_L8kH4VLVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});